version: '2'
services:
 java-servelet-app:
    build:
     context: ./demo
    volumes:
      - ./src:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    networks:
     - app-network
    environment:
      APP_NAME: 'helloservlet'
      APP_CLASS: 'mypkg'
    command: [ "run.sh" ]
 node-web-app:
   build:
     context: ./node-java
   ports:
     - 8002:8000
   environment:
     - JAVA_BACKEND=http://java-servelet-app/demo
   networks:
     - app-network
   depends_on:
     - java-servelet-app
 react-node-java:
   build:
     context: ./java-react
   ports:
     - 3005:3000
   environment:
     - REACT_APP_BACKEND_URL=http://node-web-app/
     - REACT_APP_Pharmacis=Pharmacis
     - REACT_APP_ADMIN_ROLE=Admin
   networks:
     - app-network
   depends_on:
     - node-web-app
 
networks:
  app-network:
    driver: bridge