version: '3'
services:
 java-servelet-app:
    build:
     context: ./demo
    ports:
      - "8081:8080"
    networks:
     - app-network

 node-web-app:
   build:
     context: ./node-java
   ports:
     - 8002:8000
   environment:
     - JAVA_BACKEND=http://java-servelet-app/demo/login
   networks:
     - app-network
   depends_on:
     - java-servelet-app
 react-node-java:
   build:
     context: ./java-react
   ports:
     - 3005:3000
   environment:
     - REACT_APP_BACKEND_URL=http://node-web-app/
     - REACT_APP_Pharmacis=Pharmacis
     - REACT_APP_ADMIN_ROLE=Admin
   networks:
     - app-network
   depends_on:
     - node-web-app
 
networks:
  app-network:
    driver: bridge